CREATE TABLE fondos (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  cif TEXT NOT NULL UNIQUE,
  iban TEXT,
  creado_en TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE fondos ENABLE ROW LEVEL SECURITY;
